FORMAT: 1A
HOST: https://invacaretest-a493523.integration.us2.oraclecloud.com/integration/flowapi/rest/ADD_CUSTOMER_DATA/v01

# User Data Insertion into OIC API

User Data Insertion into OIC API is a **REST** API that processes a **POST** request to the REST endpoint which performs operation and inserts data into the database.

## Operations [/new_customer_data]

### Insert Operation [POST]

Inserts data into database using Oracle Integration Cloud Service

+ Request (application/json)

        {
          "CustomerInfo": 
          {
                "CustomerNumber": "12345678",
                "CustomerID": "JMK123",
                "CustomerName": "Jaimik Bhatt",
                "Address": 
                {
                      "Address1": "3515 SW 39 BLvd",
                      "Address2": "Archer Rd",
                      "City": "Gainesville",
                      "ZipCode": "32608",
                      "State": "FL"
                },
            "OrgID": "Lab64"
          }
        }

+ Response 201 (application/json)

    + Headers
    
            Authorization: Basic
    
    + Body
    
            {
              "StatusMsg": "'Success!'"
            }